export default {
  LOGIN_REDIRECT_PATH: '/',
  SET_LEAGUES: 'SET_LEAGUES',
  SET_MATCHES: 'SET_MATCHES',
  SET_MATCH: 'SET_MATCH',
  SET_CLUB: 'SET_CLUB',
  SET_CLUBS: 'SET_CLUBS',
  SET_TEAM: 'SET_TEAM',
  SET_PLAYERS: 'SET_PLAYERS',
  SET_PLAYERS_HOMEAWAY: 'SET_PLAYERS_HOMEAWAY',
  SET_RECORDS: 'SET_RECORDS'
}